# .github/workflows/ci.yml
name: Python CI/CD

on:
  push:
    branches: [ main ] # Dispara o workflow quando houver um push na branch main
  pull_request:
    branches: [ main ] # Dispara o workflow quando um pull request é aberto ou atualizado na branch main

jobs:
  test:
    runs-on: ubuntu-latest # O sistema operacional da máquina virtual (runner) que executará o job

    steps:
    - name: Checkout repository # Passo para clonar o seu repositório
      uses: actions/checkout@v4

    - name: Set up Python # Passo para configurar o ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Garanta que esta versão corresponda à do seu Dockerfile ou Python local

    - name: Install dependencies # Passo para instalar as dependências do requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests # Passo para executar os testes usando pytest
      run: |
        pytest # Executa o pytest, que vai encontrar e rodar os testes na pasta 'tests/'